name: macOS Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (e.g. v1.0.0)"
        required: true
        default: "v1.0.0"
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"
          channel: "stable"

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Install dependencies
        run: flutter pub get

      - name: Build macOS
        run: flutter build macos --release

      - name: Create DMG
        run: |
          cd build/macos/Build/Products/Release
          create-dmg \
            --volname "YouTube Downloader" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "youtube_downloader_flutter.app" 200 190 \
            --hide-extension "youtube_downloader_flutter.app" \
            --app-drop-link 600 185 \
            "YouTube Downloader.dmg" \
            "youtube_downloader_flutter.app"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/macos/Build/Products/Release/YouTube Downloader.dmg
            build/macos/Build/Products/Release/youtube_downloader_flutter.app
          draft: false
          prerelease: false
          name: Release ${{ github.event.inputs.version || github.ref_name }}
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
          body: |
            YouTube Downloader ${{ github.event.inputs.version || github.ref_name }}

            ### Downloads
            - macOS DMG Installer
            - macOS App Bundle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
